### ISSUE TITLE
Intermittent `EMFILE` errors on initialization

### ISSUE THREAD

**Issue by dividedmind** [getappmap/vscode-appland#511]
Sometimes on initialization so many files are opened an EMFILE error gets thrown (at different places), for example:
```
Error: spawn /node_modules.asar.unpacked/@vscode/ripgrep/bin/rg EMFILE
```
```
Error: EMFILE: too many open files, open '/Users/user/Projects/project/api/.idea/.gitignore'
```

This seems to happen especially on darwin. We should examine our initialization code to make sure we aren't opening extra files or leaving them open, with an eye toward optimizing it and possibly delaying some work until after we've initialized. It's possible on darwin fswatches also open files, so we need to make sure we're only watching what we need.

Also, it would be good if the initalization could recover from these errors.

**Comment by lachrist** [comment]
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?redirect_uri=https%3A%2F%2Fportal.azure.com%2Fsignin%2Findex%2F&response_type=code%20id_token&scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2Fuser_impersonation%20openid%20email%20profile&state=OpenIdConnect.AuthenticationProperties%3DunI5Je_MR3VGAjk-RY56BeCM-Iqs8oSL666lLvVJ9g10HY38kPoSVV3KUew9YmDKy6BSVPpyTcu7-zHfAsWe3EZpgj1zYdyImr08_KobiTSupSn8kOZNHX63E_9medPkhdSuSesQmljIHyIpD51RUiiskarS1M_Lc0ThnP3V4u6XU_GIfX9BzsZzVcfOP-Y87oeogX1TDyYbydlV-Lkm5fdd6zIjMZR6Rp0dK0G8U3lPjSoTFUpG5n2St9z58ENGEU_PmHo7FKjpS_9TdRf5EejMy_gPpeIdSc7N0o-qoOb7IZBa7xo2Ix6d2bnUBSdophANeXivYbhipIfqPoiM3MuX9o_mXhkeMc56ZcyEzJHSqe9Tl9tXa3NO15HUCsqZiBSLlZuvy5MSUl9urOO0kPF5JHhlewCoW3smjZC9NgZAX6z20681GUMYhEf_4hdlYC9QQcHBf_I48J9Ev0AetqUANflAaicgDadGG4m7MAg&response_mode=form_post&nonce=638047198792995927.NWYzNWRhYWYtMGUxYS00MjY0LWI2ZmUtOTM2YjgzZjZjNjg0NjRhNDFiYmEtYjQ5Yi00ZDUyLWI4MzQtMmNiZTU1M2VhYjQw&client_id=c44b4083-3bb0-49c1-b47d-974e53cbdf3c&site_id=501430&client-request-id=92491c4d-6aee-4160-9ca9-7e7f9b74488a&x-client-SKU=ID_NET472&x-client-ver=6.22.1.0

**Comment by symwell** [comment]
One reason it happens so much on Darwin is the limit of `256` file descriptors on Darwin.
```
% ulimit -a | grep 'file descriptors'
-n: file descriptors                256
```
On Ubuntu 20 Linux this limit is `1024`.

**Comment by symwell** [comment]
Saw `ENFILE` instead of `EMFILE`
[log](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222023-01-10T19%3A56%3A19.838Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222023-01-10T19%3A56%3A19.838Z%22))%20and%20session_Id%20%3D%3D%20%2244ad597c-dcf9-4a53-8462-4116d8c307671673380517655%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)
[slack](https://applanding.slack.com/archives/C02DU9210Q2/p1673380752808539)
```
Error: spawn /node_modules.asar.unpacked/@vscode/ripgrep/bin/rg ENFILE
    at O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2026:6570)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2049:4934
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2049:3425
```

**Comment by dividedmind** [comment]
Seems like they're related. However, we're not spawning rg directly, is this error even relevant to our code?

**Comment by kgilpin** [comment]
No plan to implement
