### ISSUE TITLE
Unhandled network errors while retrieving end-user yarn dependencies

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#545]
- `RequestError: self signed certificate in certificate chain`
- `RequestError: getaddrinfo ENOTFOUND`
- `RequestError: unable to get local issuer certificate`
- `RequestError: getaddrinfo EAI_AGAIN`
- `RequestError: connect ETIMEDOUT`
- `RequestError: connect ECONNREFUSED`

**Comment by ahtrotta** [comment]
[Here's](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-12-15T02%3A31%3A25.535Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-12-15T02%3A31%3A25.535Z%22))%20and%20session_Id%20%3D%3D%20%22505940f5-0226-43ff-9a1c-a9acf1117c3b1670977245854%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception) another one:
```
RequestError: write EPROTO 31273096:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:594:SSL alert number 40
```

**Comment by symwell** [comment]
Another one:
```
Stdout: ➤ YN0001: │ RequestError: unable to verify the first certificate
```
[Slack](https://applanding.slack.com/archives/C02DU9210Q2/p1672988059542299)
[log](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222023-01-06T06%3A50%3A59.287Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222023-01-06T06%3A50%3A59.287Z%22))%20and%20session_Id%20%3D%3D%20%22453bf386-7bdf-4a85-a4d4-3435139c16dd1672987778147%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)

```
Error: Failed to install dependencies
Exit code: 1
Signal: null
Stdout: ➤ YN0000: ┌ Resolution step

Stdout: ➤ YN0001: │ RequestError: unable to verify the first certificate
at ClientRequest.<anonymous> (c:\Users\TEST\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:222:14361)
at Object.onceWrapper (node:events:510:26)
at ClientRequest.emit (node:events:402:35)
at ClientRequest.o.emit (c:\Users\TEST\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:217:90453)
at TLSSocket.socketErrorListener (node:_http_client:447:9)
at TLSSocket.emit (node:events:390:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
at TLSSocket.emit (node:events:390:28)
at TLSSocket._finishInit (node:_tls_wrap:944:8)
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)

Stdout: ➤ YN0000: └ Completed in 0s 551ms
➤ YN0000: Failed with errors in 0s 556ms

at ChildProcess.<anonymous> (\out\extension.js:39013:32)
at Object.onceWrapper (node:events:510:26)
at ChildProcess.emit (node:events:402:35)
at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by symwell** [comment]
Another one:

```
RequestError: read ECONNRESET
```
[Slack](https://applanding.slack.com/archives/C02DU9210Q2/p1672992854452229)
[log](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222023-01-06T08%3A08%3A41.589Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222023-01-06T08%3A08%3A41.589Z%22))%20and%20session_Id%20%3D%3D%20%226e5c0eb7-9f31-4c6a-933a-47734ec88f031672992375404%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)
```
Error: Failed to install dependencies
Exit code: 1
Signal: null
Stdout: ➤ YN0000: ┌ Resolution step

Stdout: ➤ YN0001: │ RequestError: read ECONNRESET
at ClientRequest.<anonymous> (c:\Users\TEST\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:222:14361)
at Object.onceWrapper (node:events:646:26)
at ClientRequest.emit (node:events:538:35)
at o.emit (c:\Users\TEST\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:217:90453)
at TLSSocket.socketErrorListener (node:_http_client:442:9)
at TLSSocket.emit (node:events:526:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)

Stdout: ➤ YN0000: └ Completed in 2m 12s
➤ YN0000: Failed with errors in 2m 12s

at ChildProcess.<anonymous> (\out\extension.js:39013:32)
at Object.onceWrapper (node:events:646:26)
at ChildProcess.emit (node:events:538:35)
at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```
