### ISSUE TITLE
`Error: Lock is already released` in CLI installation

### ISSUE THREAD

**Issue by dividedmind** [getappmap/vscode-appland#598]
We use locking to prevent parallel installation processes to run for the CLI and the scanner. I've noticed this in telemetry:
```
Error: Lock is already released
at \node_modules\proper-lockfile\lib\lockfile.js:257:1
at \node_modules\proper-lockfile\lib\adapter.js:39:1
at new Promise (<anonymous>)
at \node_modules\proper-lockfile\lib\adapter.js:30:1
at NodeProcessService.install (\src\services\nodeProcessService.ts:260:36)
at \src\extension.ts:217:7
```

It could be a fluke, or there could be a problem with our locking strategy. We should examine the code and if it seems like a fluke, we might consider swallowing this error (perhaps still sending telemetry message to monitor it) so it doesn't crash the code.

**Comment by dividedmind** [comment]
Duplicate of #558
