### ISSUE TITLE
Dependency installation errors occurring on win32

### ISSUE THREAD

**Issue by brikelly** [getappmap/vscode-appland#801]
This is occurring very frequently in the wild:

```Error: Failed to install dependencies
Exit code: 2147483651
Signal: null
Stdout: ➤ YN0000: ┌ Resolution step

Stdout: ➤ YN0002: │ swagger-parser@npm:10.0.3 doesn't provide openapi-types (p54c62), requested by @apidevtools/swagger-parser
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code

Stdout: ➤ YN0000: └ Completed in 2s 840ms
➤ YN0000: ┌ Fetch step

Stdout: ➤ YN0013: │ @appland/appmap@npm:3.93.1 can't be found in the cache and will be fetched from the remote registry

Stdout: ➤ YN0019: │ @appland-appmap-npm-3.93.0-25f9ac707c-99e7cb8946.zip appears to be unused - removing

Stdout: ➤ YN0000: └ Completed in 11s 519ms

Stdout: ➤ YN0000: ┌ Link step

Stdout: ➤ YN0000: └ Completed in 5s 929ms

Stdout: ➤ YN0000: Done with warnings in 20s 663ms

at ChildProcess.<anonymous> (\src\services\nodeProcessService.ts:238:20)
at Object.onceWrapper (node:events:628:26)
at ChildProcess.emit (node:events:525:35)
at ChildProcess.emit (node:domain:489:12)
at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)```

**Comment by dustinbyrne** [comment]
This looks likely to be the culprit

```
Stdout: ➤ YN0001: │ Libzip Error: Failed to open the cache entry for d3-color@npm:3.1.0: Not a zip archive
at Ai.makeLibzipError (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:346:12685)
at new Ai (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:346:12126)
at j (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:461:2968)
at c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:461:3032
at YS (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:422:11171)
at Vh.factory (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:461:3023)
at get baseFs [as baseFs] (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:346:39931)
at Vh.readFilePromise (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:346:37479)
at Da.readFilePromise (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:346:37486)
at ol.loadFile (c:\Users\Dustin\AppData\Roaming\Code\User\globalStorage\appland.appmap\yarn.js:422:32946)
```
